media:
  input: public/uploads
  output: /uploads
  rename: random

content:

  - name: gallery
    label: Gallery
    path: content/gallery
    type: collection
    format: yaml
    filename: "{primary}.yml"
    fields:
      - name: name
        label: Name
        type: string
        required: true
      - name: image
        label: Image
        type: image
      - name: food
        label: Food
        type: reference
        required: false
        options:
          collection: food

  - name: hours
    label: Hours
    path: content/hours.json
    type: file
    list: true
    format: json
    fields:
      - name: dayOfWeek
        label: Day of Week
        type: select
        options:
          values: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
      - name: openTime
        label: Open Time
        type: string
      - name: closeTime
        label: Close Time
        type: string

  - name: reviews
    label: Reviews
    path: content/reviews
    type: collection
    format: yaml
    filename:
      template: "{year}-{month}-{day}-{hour}:{minute}:{second}.md"
      field: create
    fields:
      - name: author
        label: Author
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: rating
        label: Rating
        type: number
        required: true
        options:
          min: 1
          max: 5
      - name: body
        label: Content
        type: text
        required: true

  - name: menus
    label: Menus
    path: content/menus
    type: collection
    format: yaml
    filename:
      template: "{primary}.yml"
      field: create

    fields:
      - name: name
        label: Name
        type: string
        required: true

      - name: description
        label: Description
        type: string
        required: false

      - name: parent
        label: Parent
        type: reference
        required: false
        options:
          collection: menus

      - name: food
        label: Food
        type: object
        list: true
        required: false
        fields:
          - name: name
            label: Name
            type: string
            required: true
          - name: price
            label: Price
            type: string
            required: true
          - name: spicy
            label: Spicy
            type: boolean
            default: false
